### ISSUE TITLE
Exception when using Irssi Connectbot as Library Project

### ISSUE THREAD

**Issue by moonzai** [irssiconnectbot/irssiconnectbot#69]
I am using Irssi ConnectBot in my application. Irssi Connectbot works perfect standalone, but I use it with my project it generates exception:

Problem while handling incoming data in relay thread
java.io.IOException: Remote end closed connection
    at org.woltage.irssiconnectbot.transport.SSH.read(SSH.java:588)
    at org.woltage.irssiconnectbot.service.Relay.run(Relay.java:116)
    at java.lang.Thread.run(Thread.java:1019)

I debugged the code, it reads 449 characters in first call of read function but in next call of read, it read 22 characters and gets stopped, then disconnect handler sends message for disconnection.

I have been in this problem for last 2 weeks, moreover I am only copy pasting code from Irssi ConnectBot. No new thing..

any help would be appreciated

Regards
Moonzai

**Comment by ericwongcm** [comment]
Use my patched repository until my patch is accepted.
https://github.com/irssiconnectbot/irssiconnectbot/pull/70
